#! /bin/bash
#Choix du questionnaire
echo -e "Choisissez un questionnaire :"
select responseQuestion in "Etienne" "Jordan";do
  case $responseQuestion in
    Etienne ) choiceQuestion="Etienne";break;;
    Jordan ) choiceQuestion="Jordan";break;;
  esac
done

if [ "$choiceQuestion" == "Etienne" ]; then
  #Code Etienne
  #Declaration des variables
  byeMoldu="Au revoir moldu.";
  choiceBonbon="";
  choiceSorcier="";
  choiceBienMal="";
  choiceSort="";
  choiceMaison="";
  choiceBalai="";
  choiceVif="";
  choiceMinistere="";
  choiceAvada="";
  choiceDoloris="";
  choiceNez="";
  choiceNoir="";

  #Debut du script
  #Premiere question qui permet de savoir si l'utilisateur est au courant du monde de la magie
  echo -e "\033[47mBonjour et bienvenue, avant de rentrer dans les détails, j'ai besoin de savoir si vous aimez les bonbons de Bertie Crochu ? \033[0m";
  select responseBonbon in "Oui" "Non" "Inconnu";do
    case $responseBonbon in
      Oui ) choiceBonbon="Oui";break;;
      Non ) choiceBonbon="Non";break;;
      Inconnu ) choiceBonbon="Inconnu";break;;
    esac
  done

  #Vu qu'il ne connait pas ces bonbons, c'est un moldu, il est donc expulsé du script
  if [ "$choiceBonbon" == "Inconnu" ]
  then
    echo $byeMoldu;
    exit;
  elif [ "$choiceBonbon" == "Oui" ] || [ "$choiceBonbon" == "Non" ];
  then
    #Seconde question pour savoir s'il est déjà sorcier
    echo -e "\033[47mEtes-vous déjà sorcier ?\033[0m";
    select responseSorcier in "Oui" "Non";do
      case $responseSorcier in
        Oui ) choiceSorcier="Oui";break;;
        Non ) choiceSorcier="Non";break;;
      esac
    done
    #Il aime pas les bonbons et il est sorcier, il a pas besoin d'une baguette de haut niveau
    if [ "$choiceBonbon" == "Non" ] && [ "$choiceSorcier" == "Oui" ]
    then
      echo -e "\033[34mVous avez une baguette de niveau 1.\033[0m";
      exit;
    #Si des moldus ont mis oui a la premiere question
    elif [ "$choiceSorcier" == "Non" ]
    then
      echo $byeMoldu;
      exit;
    elif [ "$choiceSorcier" == "Oui" ]
    then
      #Troisieme question pour savoir s'il veut faire le bien ou le mal
      echo -e "\033[47mVoulez vous faire le bien ou le mal avec votre baguette ?\033[0m";
      select responseBienMal in "Bien" "Mal";do
        case $responseBienMal in
          Bien ) choiceBienMal="Bien";break;;
          Mal ) choiceBienMal="Mal";break;;
        esac
      done

      #Premier cas : le mal avec le sort Avada Kedavra
      if [ "$choiceBienMal" == "Mal" ]
      then
        echo -e "\033[31mPour toutes baguettes vendues à destination du mal, le vendeur n'en est pas responsable, merci de votre compréhension. PS : Risque d'être envoyé à Azkaban\033[0m";
        echo -e "\033[47mAimez-vous un des sorts interdits comme Avada Kedavra ?\033[0m";
        select responseAvada in "Oui" "Non";do
          case $responseAvada in
            Oui ) choiceAvada="Oui";break;;
            Non ) choiceAvada="Non";break;;
          esac
        done
      fi
      #Si il aime bien le sort Avada
      if [ "$choiceAvada" == "Oui" ]
      then
        #Savoir s'il a un nez
        echo -e "\033[47mAvez-vous un nez ?\033[0m"
        select responseNez in "Oui" "Non";do
          case $responseNez in
            Oui ) choiceNez="Oui";break;;
            Non ) choiceNez="Non";break;;
          esac
        done
        #Si la personne n'a pas de nez, on sait deja qui c'est
        if [ "$choiceNez" == "Non" ]
        then
          echo -e "\033[34mBienvenue Monsieur, votre baguette sera prête en temps voulu.\033[0m"
          exit;
          #Si il a un nez
        else [ "$choiceNez" == "Oui" ]
          echo -e "\033[34mVous aurez une baguette de niveau 5 pour le mal.\033[0m"
          exit;
        fi
        #S'il n'aime pas le sort Avada Kedavra alors on lui propose un autre sort interdit
      elif [ "$choiceAvada" == "Non" ]
      then
        echo -e "\033[47mAimez-vous le sort Doloris ?\033[0m"
        select responseDoloris in "Oui" "Non";do
          case $responseDoloris in
            Oui ) choiceDoloris="Oui";break;;
            Non ) choiceDoloris="Non";break;;
          esac
        done
        #Si la personne n'aime pas le sort Doloris
        if [ "$choiceDoloris" == "Non" ]
        then
          echo -e "\033[34mVous aurez une baguette de niveau 4 pour le mal.\033[0m"
          exit;
          #Si elle aime bien le sort Doloris
        else
          echo -e "\033[34mVous aurez une baguette de niveau 5 pour le mal.\033[0m"
          exit;
        fi
      fi

      #Second cas : le bien
      if [ "$choiceBienMal" == "Bien" ]
      then
        echo -e "\033[47mQuel sort préférez-vous ?\033[0m";
        select responseSort in "Lumos" "Patronus" "Incendio";do
          case $responseSort in
            Lumos ) choiceSort="Lumos";break;;
            Patronus ) choiceSort="Patronus";break;;
            Incendio ) choiceSort="Incendio";break;;
          esac
        done
        #Si la personne repond Lumos ou Incendio
        if [ "$choiceSort" == "Incendio" ] || [ "$choiceSort" == "Lumos" ]
        then
          echo -e "\033[34mVous aurez une baguette de niveau 3 pour le bien.\033[0m";
          exit;
        elif [ "$choiceSort" == "Patronus" ]
        then
          echo -e "\033[47mQuelle est votre maison ?\033[0m"
          #Choisir sa maison (pas poufsoufle svp)
          select responseMaison in "Gryffondor" "Serdaigle" "Poufsoufle" "Serpentard";do
            case $responseMaison in
              Gryffondor ) choiceMaison="Gryffondor";break;;
              Serdaigle ) choiceMaison="Serdaigle";break;;
              Poufsoufle ) choiceMaison="Poufsoufle";break;;
              Serpentard ) choiceMaison="Serpentard";break;;
            esac
          done
          if [ "$choiceMaison" == "Gryffondor" ] || [ "$choiceMaison" == "Serdaigle" ] || [ "$choiceMaison" == "Poufsoufle" ] || [ "$choiceMaison" == "Serpentard" ]
          then
            echo -e "\033[47mAvez-vous un balai volant ?\033[0m";
            #Demande s'il a un balai volant
            select responseBalai in "Oui" "Non";do
              case $responseBalai in
                Oui ) choiceBalai="Oui";break;;
                Non ) choiceBalai="Non";break;;
              esac
            done
            if [ "$choiceBalai" == "Non" ]
            then
              echo -e "\033[34mVous aurez une baguette de niveau 3 pour faire le bien.\033[0m";
              exit;
            elif [ "$choiceBalai" == "Oui" ]
            then
              #Savoir s'il a deja attrapé le vif d'or
              echo -e "\033[47mAvez-vous déjà attrapé un vif d'or ?\033[0m";
              select responseVif in "Oui" "Non";do
                case $responseVif in
                  Oui ) choiceVif="Oui";break;;
                  Non ) choiceVif="Non";break;;
                esac
              done
              if [ "$choiceVif" == "Oui" ]
              then
                echo -e "\033[34mVous aurez une baguette de niveau 5 pour le bien.\033[0m";
                exit;
              else
                echo -e "\033[34mVous aurez une baguette de niveu 4 pour le bien\033[0m";
                exit;
              fi
            fi
          fi
        fi
      fi
    fi
  fi

  #Code de Jordan
else
cyanclair='\e[1;36m'
rouge='\033[31m '
neutre='\033[0m'

#1ère question :
echo -e "${rouge} As-tu la Parkinson ? ${neutre}";
premq="";
select response in 'Oui' 'Non' ;do
    case $response in
  Oui ) option1='stabilisante';break;;
  Non ) option1='fixe';break;;
    esac
done

#2ème question :
echo -e "${rouge}Es-tu gauché, droitié ou ambidextre ? ${neutre}";
deuxq="";
select response2 in 'Droitié' 'Gauché' 'Ambidextre';do
    case $response2 in
  Droitié )  option2='pour droitié';break;;
  Gauché ) option2='pour gauché';break;;
  Ambidextre ) option2='pour ambidextre';break;;
    esac
done

#3ème question :
echo -e "${rouge}Es-tu adroit ? ${neutre}"
troisq="";
select response3 in 'Oui' 'Non' ;do
    case $response3 in
  Oui ) option3='fine';break;;
  Non ) option3='grosse';break;;
    esac
done

#4ème question :
echo -e "${rouge}Ton avant-bras fait-il plus de 30 cm : ${neutre}";
quatreq="";
select response4 in 'Oui' 'Non';do
    case $response4 in
  Oui ) option4='Grande';break;;
  Non ) option4='Courte';break;;
    esac
done

#5ème question :
echo -e "${rouge}Tu es plutôt : ${neutre}"
cinqq="";
select response5 in 'étourdi' 'appliqué' ;do
    case $response5 in
  étourdi ) option5='bracelet attaché au poignet';break;;
  appliqué  ) option5='';break;;
    esac
done

#6ème question:
echo -e "${rouge}Tu as trois caractéristiques pour ta baguette, tu préfères qu elle soit : ${neutre}"
sixq="";
select response6 in 'estéthique' 'confortable' 'puissante';do
    case $response6 in
  'estéthique' ) option6='estéthique';break;;
  confortable ) option6='confortable';break;;
  puissante ) option6='puissante';break;;
    esac
done

#7ème question
if [ $option6 == "estéthique" ]
  then echo -e "${rouge}Il te reste deux caractéristique à choisir, laquelle des deux préfères-tu ? ${neutre}"
      septq="";
      select response7 in 'confortable' 'puissante';do
          case $response7 in
        confortable ) option7='confortable';break;;
        puissante ) option7='puissante';break;;
          esac
        done
          if [ $option7 == 'confortable' ]
              then
                  option10='puissante';

          elif [ $option7 == 'puissante'];
              then
                option10='confortable'


          fi


  elif [ $option6 == "confortable" ]
  then
    echo -e "${rouge}Il te reste deux caractéristique à choisir, laquelle des deux préfères-tu ? ${neutre}";
    septq="";
    select response7 in 'estéthique' 'puissante';do
        case $response7 in
      estéthique  ) option7='estéthique';break;;
      puissante ) option7='puissante';break;;
              esac
      done
        if [ $option7 == "esthétique" ]
          then
            option10='puissante';
        elif [ $option7 == 'puissante' ];
          then
            option10='esthétique'
        fi


  else
    echo -e "${rouge}Il te reste deux caractéristique à choisir, laquelle des deux préfères-tu ?${neutre}";
    septq="";
    select response7 in 'estéthique' 'confortable';do
        case $response7 in
      estéthique  ) option7='esthéthique';break;;
      confortable ) option7='confortable';break;;

        esac
    done

    if [ $option7 == "esthéthique" ];
      then
        option10='confortable';
    elif [ $option7 == 'confortable' ];
      then
        option10='esthétique';
    fi
fi


#8ème question :
echo -e "${rouge}Tes intentions sont : ${neutre}";
huitq="";
select response8 in 'Bonnes' 'Mauvaises' ;do
    case $response8 in
        Bonnes ) option8='légal';break;;
        Mauvaises ) option8='illégal';break;;
    esac
  done

#9ème question :
echo -e "${rouge}Consommez vous régulièrement de l alcool ?${neutre}";
neufq="";
select response9 in 'Oui' 'Non' ;do
  case $response9 in
    Oui ) option9="";break;;
    Non ) option9="";break;;
  esac
done
#10ème question :
if [ "$response9" == "Oui" ]
  then
  echo -e "${rouge}Êtes-vous aveugle ?${neutre}"
  dixq="";
    select response10 in 'Oui' 'Non';do
      case $response10 in
        Oui ) option9='Capteur sensitif afin de prendre la baguette dans le bon sens';break;;
        Non ) option9='Flèche désignant le sens de la baguette';break;;
      esac
  done
elif [ "$response9" == "Non" ]
  then
  echo -e "${rouge}Consommez-vous de la drogue régulièrement ? ${neutre}"
    select responsive10 in 'Oui' 'Non' ;do
      case $responsive10 in
        Oui ) option9="";break;;
        Non ) option9="";break;;
      esac
    done
fi

#11ème question :

if [ "$responsive10" == "Oui" ]
  then
    echo -e "${rouge}Êtes-vous aveugle ?${neutre}"
    select responsive11 in 'Oui' 'Non';do
      case $responsive11 in
        Oui ) option9="capteur sensitif afin de prendre la baguette dans le bon sens";break;;
        Non ) option9="";break;;
      esac
  done
fi

echo 'Voici votre baguette idéal, elle contient les options suivantes : '
echo '-' $option1
echo '-' $option2
echo '-' $option3
echo '-' $option4
# if [ "$option5" == '' ];
#   then
#
# fi
# if [ "$option8" == '' ];
#  then
#
# fi

echo '-' $option9
echo 'Ses principales caractérisitques sont'
echo '1 -' $option6
echo '2 -' $option7
echo '3 -' $option10


cat <<"EOF"

        _            _.,----,
__  _.-._ / '-.        -  ,._  \)
|  `-)_   '-.   \       / < _ )/" }
/__    '-.   \   '-, ___(c-(6)=(6)
, `'.    `._ '.  _,'   >\    "  )
:;;,,'-._   '---' (  ( "/`. -='/
;:;;:;;,  '..__    ,`-.`)'- '--'
;';:;;;;;'-._ /'._|   Y/   _/' \
  '''"._ F    |  _/ _.'._   `\
         L    \   \/     '._  \
  .-,-,_ |     `.  `'---,  \_ _|
  //    'L    /  \,   ("--',=`)7
 | `._       : _,  \  /'`-._L,_'-._
 '--' '-.\__/ _L   .`'         './/
             [ (  /
              ) `{
               \__)

EOF
fi


